#!/bin/bash

#SBATCH --job-name=multinode-example
#SBATCH --nodes=8
#SBATCH --ntasks=8
#SBATCH --gres=gpu:a30:1
#SBATCH --cpus-per-task=2

export MASTER_ADDR=$(scontrol show hostname ${SLURM_NODELIST} | head -n 1)

ml Python
srun python -m torch.distributed.launch --use_env \
--nnodes 8 \
--nproc_per_node 1 \
--rdzv_id $RANDOM \
--rdzv_backend c10d \
--rdzv_endpoint $MASTER_ADDR:29500 \
multinode.py 